---
title: "Examination of Exports from Oregon"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Map of Export Destinations 2010-2020  {data-width=650}
================================================================

### Map of Export Destinations 2010-2020 

```{r}

library(ggplot2)
myWeb="https://github.com/SamHenkels47/project3/raw/main/"
someVars=readRDS(file=url(paste0(myWeb,"Map1.rds")))
plot(someVars)
```

Export Categories 2010-2020 {data-width=650}
================================================================

### Export Categories 2010-2020

```{r}
library(ggplot2)
myWeb="https://github.com/SamHenkels47/samhenkels2/raw/main/"
someVars=readRDS(file=url(paste0(myWeb,"chart2.rds")))
plot(someVars)
```

Destination of Oregon's Semiconductors  {data-width=10000}
================================================================

### Destination of Oregon's Largest Export Product - Semiconductors

```{r}
library(ggplot2)
myWeb="https://github.com/SamHenkels47/Project-1/raw/main/"
someVars=readRDS(file=url(paste0(myWeb,"chart2.rds")))
plot(someVars)
```
